TITLE="Beej's Guide to Network Concepts"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v1.11.1, Copyright © September 28, 2025"

GUIDE_ID=bgnet0
BGBSPD_BUILD_DIR?=../../bgbspd
WEB_IMAGES=$(wildcard *.svg *.png)
EPUB_SVGS=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make

